<a href="https://colab.research.google.com/github/shreyash22rx/Numpy_notebooks/blob/main/advanced_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy Array vs Python List

In [ ]:
# python list in terms of speed

a = [i for i in range(10000000)]
b = [i for i in range(10000000,20000000)]

c = []

import time

start = time.time()
for i in range(len(a)):
  c.append(a[i] + b[i])
print(time.time()-start)


2.598212718963623


In [ ]:
# np array

import numpy as np

a = np.arange(10000000)
b = np.arange(10000000,20000000)

start = time.time()
c = a+b
print(time.time()-start)


0.042577505111694336


In [ ]:
# list in terms of memory

a = [i for i in range(10000000)]
import sys
sys.getsizeof(a)

89095160

In [ ]:
a = np.arange(10000000)
sys.getsizeof(a)

80000112

In [ ]:
# if we change size of int
a = np.arange(10000000,dtype='int32')
sys.getsizeof(a)

40000112

# Advanced Indexing

In [ ]:
# normal indexing and slicing

a = np.arange(12).reshape(4,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
a[1:3,1:3]

array([[4, 5],
       [7, 8]])

In [ ]:
# to overcome some limitations of normal indexing, we use fancy indexing

a = np.arange(24).reshape(6,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

**Fancy Indexing**

In [ ]:
# now, we want 1st row 2nd row, and last so it does not formany pattern so we use fancy indexing

a[[0,1,5]]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [20, 21, 22, 23]])

In [ ]:
a[:,[0,1,3]]

array([[ 0,  1,  3],
       [ 4,  5,  7],
       [ 8,  9, 11],
       [12, 13, 15],
       [16, 17, 19],
       [20, 21, 23]])

**Boolean Indexing**

In [ ]:
a = np.random.randint(1,100,24).reshape(6,4)
a

array([[75, 35,  6, 76],
       [94, 46, 47, 31],
       [ 1, 12, 39,  2],
       [94,  6, 11, 57],
       [85, 61, 31, 58],
       [73,  3,  4, 61]])

In [ ]:
# a > 50

a[a > 50]

array([75, 76, 94, 94, 57, 85, 61, 58, 73, 61])

In [ ]:
# a is even

a[ a % 2 == 0 ]

array([ 6, 76, 94, 46, 12,  2, 94,  6, 58,  4])

In [ ]:
# a > 50 and a is even

a[(a > 50) & (a%2 == 0)]

array([76, 94, 94, 58])

In [ ]:
# a not divisible by 7

a[a%7 != 0]

array([75,  6, 76, 94, 46, 47, 31,  1, 12, 39,  2, 94,  6, 11, 57, 85, 61,
       31, 58, 73,  3,  4, 61])

# Broadcasting

* Broadcasting refers to how numpy treats arrays with different shape during arithematic operation
* smaller array is broadcasted over larger array

In [ ]:
a = np.arange(12).reshape(4,3)
b = np.arange(3)

print(a)
print(b)
print(a+b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[0 1 2]
[[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]
 [ 9 11 13]]


In [ ]:
# this will not give output because (3,4) and (3,3) cant be added up

a = np.arange(12).reshape(3,4)
b = np.arange(3)

print(a)
print(b)
print(a+b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[0 1 2]


ValueError: ignored

In [ ]:
a = np.arange(3).reshape(1,3)
b = np.arange(3).reshape(3,1)

print(a)
print(b)
print(a+b)

[[0 1 2]]
[[0]
 [1]
 [2]]
[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [ ]:
a = np.arange(3).reshape(1,3)
b = np.arange(4).reshape(4,1)

print(a)
print(b)
print(a+b)

[[0 1 2]]
[[0]
 [1]
 [2]
 [3]]
[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]]


In [ ]:
a = np.arange(12).reshape(3,4)
b = np.arange(12).reshape(4,3)

print(a)
print(b)

print(a+b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


ValueError: ignored