<a href="https://colab.research.google.com/github/shreyash22rx/Numpy_notebooks/blob/main/session_13_numpy_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>



# Creating Numpy Arrays




In [ ]:
# np.array

import numpy as np
a = np.array([1,2,3])
print(a)

[1 2 3]


In [ ]:
# 2D and 3D array

b = np.array([[1,2],[3,4]])
print(b)


[[1 2]
 [3 4]]


In [ ]:
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
 # creating nparray of custom dtype

a = np.array([1,2,3],dtype=float)
print(a)

[1. 2. 3.]


In [ ]:
# np.arange

np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [ ]:
# .reshape() method

np.arange(0,10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
# np.ones()
import numpy as np
a = np.ones((3,4))
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
# np.zeros()

a = np.zeros((3,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
# np.random()

a = np.random.random((3,4))
a

array([[0.18570706, 0.78214383, 0.80423128, 0.71039705],
       [0.42697067, 0.55804385, 0.47648589, 0.25326408],
       [0.34345124, 0.05834695, 0.1194122 , 0.53550591]])

In [ ]:
# np.linspace()

a = np.linspace(-10,10,10)
print(a)

[-10.          -7.77777778  -5.55555556  -3.33333333  -1.11111111
   1.11111111   3.33333333   5.55555556   7.77777778  10.        ]


In [ ]:
# np.identity()

a = np.identity(2)
a

array([[1., 0.],
       [0., 1.]])

# Array Attributes

In [ ]:
a1 = np.arange(10)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [ ]:
print(a1)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
print(a2)

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]


In [ ]:
print(a3)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


1) "ndim"

In [ ]:
a1.ndim

1

In [ ]:
a2.ndim

2

In [ ]:
a3.ndim

3

2).  ".shape"

In [ ]:
a1.shape

(10,)

In [ ]:
a2.shape

(3, 4)

In [ ]:
a3.shape

(2, 2, 2)

3) "size"

In [ ]:
a1.size

10

In [ ]:
a2.size

12

In [ ]:
a3.size

8

4) "itemsize"

In [ ]:
a1.itemsize

8

In [ ]:
a2.itemsize

8

In [ ]:
a3.itemsize

8

5) "dtype"

In [ ]:
a1.dtype

dtype('int64')

In [ ]:
a2.dtype

dtype('float64')

In [ ]:
a3.dtype

dtype('int64')

# changing dtype


astype

In [ ]:
a3.dtype

dtype('int64')

In [ ]:
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

# array operations

In [ ]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

In [ ]:
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
# scalar operation

# arithematic operations

a1 *3

array([[ 0,  3,  6,  9],
       [12, 15, 18, 21],
       [24, 27, 30, 33]])

In [ ]:
a1 ** 2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [ ]:
# relational

a2 > 5

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [ ]:
a1 <1

array([[ True, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [ ]:
a1 == a2


array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [ ]:
# vector operations

# arithematic

a1 + a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [ ]:
a1 * a2

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

# Array Functions

In [ ]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[30., 64., 45.],
       [84., 23., 19.],
       [80., 72., 31.]])

In [ ]:
# min/max/sum/prod

# 0 -> col. 1 -> row

print(np.min(a1))
print(np.min(a2))
print(np.min(a1,axis=0))
print(np.min(a2,axis=0))

print(np.max(a1))
print(np.max(a2))

print(np.sum(a1))
print(np.sum(a2))

19.0
12
[30. 23. 19.]
[12 13 14 15]
84.0
23
448.0
210


In [ ]:
# mean/median/sd/var

print(np.mean(a1))
print(np.median(a1))
print(np.std(a1))
print(np.var(a1))

49.77777777777778
45.0
24.063701469122776
579.0617283950617


In [ ]:
# trignometric functions

np.sin(a1)

array([[-0.98803162,  0.92002604,  0.85090352],
       [ 0.73319032, -0.8462204 ,  0.14987721],
       [-0.99388865,  0.25382336, -0.40403765]])

In [ ]:
# dot product

a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

In [ ]:
np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [ ]:
# log and exponents

np.log(a1)

array([[3.40119738, 4.15888308, 3.80666249],
       [4.4308168 , 3.13549422, 2.94443898],
       [4.38202663, 4.27666612, 3.4339872 ]])

In [ ]:
np.exp(a2)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04]])

In [ ]:
# round/floor/ceil

a = np.random.random((2,3)) * 100
a

array([[66.79078899, 38.68562714, 38.48280898],
       [93.14918913, 81.49470988, 50.58581944]])

In [ ]:
np.round(a)

array([[67., 39., 38.],
       [93., 81., 51.]])

In [ ]:
np.floor(a)

array([[66., 38., 38.],
       [93., 81., 50.]])

In [ ]:
np.ceil(a)

array([[67., 39., 39.],
       [94., 82., 51.]])

# Indexing and slicing

In [ ]:
import numpy as np

In [ ]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

**Indexing**

In [ ]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# indexing is similar to list

print(a1[0])
print(a1[-1])

0
9


In [ ]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
# getting the element 6
print(a2[1,2]) # first parameter specifies the row index and second column specifies the column index

6


In [ ]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
# printing element 5

print(a3[1,0,1])      # a 3D matrix consists of 2D matrices, 1st parameter indicates the index of 2D matrix

5


**Slicing**

In [ ]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# fetching values
a1[2:5]

array([2, 3, 4])

In [ ]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
# getting only 1st row

a2[0,:]

array([0, 1, 2, 3])

In [ ]:
# getting 3rd column
a2[:,2]

array([ 2,  6, 10])

In [ ]:
# getting 5,6,9,10
a2[1:3,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [ ]:
# getting 0,3,8,11

a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [ ]:
# getting 1,3,9,11

a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [ ]:
# printing 4,7
a2[1,0::3]

array([4, 7])

In [ ]:
# printing 3,11
a2[0::2,-1]

array([ 3, 11])

In [ ]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
# 2nd 2D array of 3D array

a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [ ]:
# 3rd 2D array of 3D array

a3[2]

array([[18, 19, 20],
       [21, 22, 23],
       [24, 25, 26]])

In [ ]:
# 1st and 3rd 2D array

a3[0::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
# 2nd row of 1st 2D array : 3,4,5

a3[0,1,:]

array([3, 4, 5])

In [ ]:
# 2nd column of 3rd 2D array. :18,22,25

a3[2,:,1]

array([19, 22, 25])

In [ ]:
# 22,23,25,26

a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [ ]:
# 0,2,18,20

a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

# Iterating

In [ ]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
for i in a1:
  print(i)

0
1
2
3
4
5
6
7
8
9


In [ ]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
for i in a2:
  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [ ]:
# to print single elements from 2D array

for i in np.nditer(a2):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11


In [ ]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
for i in a3:
  print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [ ]:
for i in np.nditer(a3):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


# Reshaping

In [ ]:
# Transpose

a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
np.transpose(a2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [ ]:
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [ ]:
# ravel => converts any dimension of array into single dimension
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

# Stacking

In [ ]:
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)

In [ ]:
# horizontal stacking


np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [ ]:
# vertical stacking

np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

# Splitting

In [ ]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [ ]:
np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]